/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sprint1;

import com.formdev.flatlaf.FlatDarkLaf;
import com.mysql.cj.jdbc.JdbcStatement;
import javax.swing.UIManager;
import database.conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.PreparedStatement;




/**
 *
 * @author canta
 */
public class VerRegistropublicaciones extends javax.swing.JFrame {

    /**
     * Creates new form publicaciones
     */
     conexion jdbc = new conexion();
     
     
  
    
    public VerRegistropublicaciones() {
        initComponents();
         pack();
        setLocationRelativeTo(null);
        jdbc.conctar();
        mostrarRegistros();
       // mostrar();    
        
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public void sizeName(JTextField registros, int size, java.awt.event.KeyEvent evt){
        // Verifica que el texto no exceda el amañó máximo
        if(registros.getText().trim().length() == size){
            // Cancela el evento y no ingresa el carácter presionada
            evt.consume();
        }
    }
     /**
      a.add(registro);
                     Object[] objec;
            for (int i = 0; i < a.size(); i++) {
                System.out.println(a.get(i));
                   objec = a.toArray();
                 modelo.addRow(objec);
            }
      */
    public void mostrarRegistros(){
        //String [] registroProf = new String[1];
        
         DefaultTableModel modelo=new DefaultTableModel ();
            modelo.addColumn("Registro");
            tablaregistro.setModel(modelo);
        try {
             
            String query = "select * from registroprof;";
            
            ResultSet consulta = jdbc.consultarBD(query);
            while(consulta.next()){
                
                String registro = consulta.getString("registro2");
                String[] rowData = {registro};
                modelo.addRow(rowData);
               
            
            }
         
            
            System.out.println("---------------------");

             

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaregistro = new javax.swing.JTable();
        nuevovalor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE  PUBLICACIONES");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("Editar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        tablaregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Registro"
            }
        ));
        tablaregistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaregistroMouseClicked(evt);
            }
        });
        tablaregistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaregistroKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tablaregistro);

        nuevovalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevovalorActionPerformed(evt);
            }
        });
        nuevovalor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nuevovalorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nuevovalorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nuevovalorKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese para editar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminar)
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nuevovalor, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(nuevovalor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(eliminar))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            // Obtener el nuevo valor editado por el usuario
    String nuevoValor = nuevovalor.getText();
    
    // Verificar si se ha editado algún valor
    if (nuevoValor.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un nuevo valor antes de editar.");
        return;
    }
    
    // Obtén la fila seleccionada en la tabla
    int filaSeleccionada = tablaregistro.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un registro para editar.");
    } else {
        // Obtiene el valor actual de la celda de la columna "Registro" en la fila seleccionada
        String registroAEditar = (String) tablaregistro.getValueAt(filaSeleccionada, 0);
        try {
            // Crea una sentencia SQL para actualizar el registro en la base de datos
            String query = "UPDATE registroprof SET registro2 = ? WHERE registro2 = ?";

            // Prepara la declaración
            PreparedStatement preparedStatement = jdbc.getConctar().prepareStatement(query);
            preparedStatement.setString(1, nuevoValor);
            preparedStatement.setString(2, registroAEditar);

            // Ejecuta la sentencia SQL para actualizar el registro
            int filasAfectadas = preparedStatement.executeUpdate();

            if (filasAfectadas > 0) {
                // Registro actualizado con éxito
                JOptionPane.showMessageDialog(this, "Registro actualizado con éxito.");
                // Actualiza la tabla de registros
                mostrarRegistros();
                
                // Limpiar el campo "nuevovalor" y deshabilitar la edición
                nuevovalor.setText("");
                nuevovalor.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el registro.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el registro: " + e.getMessage());
        }
    }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
    // Obtén la fila seleccionada en la tabla
    int filaSeleccionada = tablaregistro.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un registro para eliminar.");
    } else {
        // Obtiene el valor de la celda de la columna "Registro" en la fila seleccionada
        String registroAEliminar = (String) tablaregistro.getValueAt(filaSeleccionada, 0);

        try {
            // Crea una sentencia SQL para eliminar el registro en la base de datos
            String query = "DELETE FROM registroprof WHERE registro2 = ?";

            // Prepara la declaración
            PreparedStatement preparedStatement = jdbc.getConctar().prepareStatement(query);
            preparedStatement.setString(1, registroAEliminar);

            // Ejecuta la sentencia SQL para eliminar el registro
            int filasAfectadas = preparedStatement.executeUpdate();

            if (filasAfectadas > 0) {
                // Registro eliminado con éxito
                JOptionPane.showMessageDialog(this, "Registro eliminado con éxito.");
                // Actualiza la tabla de registros
                mostrarRegistros();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el registro.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el registro: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_eliminarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         setVisible(false);
        publicaciones interfaz = new publicaciones();
        interfaz.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
          // Verificar si se ha seleccionado una fila en la tabla
    int filaSeleccionada = tablaregistro.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un registro para editar.");
    } else {
        // Obtener el valor actual de la fila seleccionada
        String valorActual = (String) tablaregistro.getValueAt(filaSeleccionada, 0);
        
        // Mostrar el valor actual en el campo "nuevovalor"
        nuevovalor.setText(valorActual);
        
        // Habilitar la edición del campo "nuevovalor"
        nuevovalor.setEditable(true);
    }
    }//GEN-LAST:event_jButton2MouseClicked

    private void tablaregistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaregistroKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tablaregistroKeyTyped

    private void tablaregistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaregistroMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tablaregistroMouseClicked

    private void nuevovalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevovalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevovalorActionPerformed

    private void nuevovalorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevovalorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevovalorKeyPressed

    private void nuevovalorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevovalorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevovalorKeyReleased

    private void nuevovalorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevovalorKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_nuevovalorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerRegistropublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerRegistropublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerRegistropublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerRegistropublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerRegistropublicaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nuevovalor;
    private javax.swing.JTable tablaregistro;
    // End of variables declaration//GEN-END:variables
}
